In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [12]:
np.array(l)

array([1, 2, 3, 4, 5])

In [7]:
l1 = [1,2,3,4, "rulu", 253.373, True]

In [13]:
a1 = np.array(l1)

In [16]:
a2 = np.array([[1,2,3],[4,5,6]])

In [17]:
a3= np.array([[[1,2,3],[4,5,6], [6,7,8]]])

In [18]:
a1

array(['1', '2', '3', '4', 'rulu', '253.373', 'True'], dtype='<U32')

In [ ]:
#a1 can be represented using only 1 axis as it is only 1 dimensional

In [ ]:
#index starts from 0 on both rows and columns

In [19]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#a2 can be represented in x and y axis using the column in x-axis and rows in y-axis

In [20]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [ ]:
#a3 can be represented in x, y and z axis as it is 3 dimensional array.
#x in horizontal, y in vertical and z in diagonal axis

In [21]:
a1.ndim

1

In [23]:
a2.ndim

2

In [26]:
a3.ndim

3

In [27]:
a1.size

7

In [28]:
a2.size

6

In [29]:
a3.size

9

In [31]:
a1.shape


(7,)

In [32]:
a2.shape


(2, 3)

In [33]:
a3.shape

(1, 3, 3)

In [ ]:
#1 represemts 1 matrix 3 rows and 3 columns

In [37]:
np.random.randint(2,50, (2,3,4))

array([[[ 5, 29, 29, 24],
        [37, 30, 24, 41],
        [43, 20,  7, 21]],

       [[27, 35, 28, 12],
        [43, 18,  6, 27],
        [47, 11, 17, 21]]])

In [38]:
# generates numbers between 2-50 and 2 matrices with 3 rows and 4 columns


In [39]:
np.random.rand(2,3)

array([[0.14056919, 0.46961643, 0.01609964],
       [0.57054151, 0.61644691, 0.29181584]])

In [42]:
np.random.rand(4,4)

array([[0.11053599, 0.36575613, 0.82442852, 0.1751534 ],
       [0.56113123, 0.25759843, 0.84725603, 0.76852137],
       [0.15577706, 0.29743364, 0.87266841, 0.04360167],
       [0.70523897, 0.9904799 , 0.22801529, 0.71318936]])

In [44]:
a4 = np.random.randn(4,4)

In [45]:
a4

array([[ 0.21580445,  0.29138881,  1.71443884, -1.12602486],
       [-0.58807136,  1.26883275, -0.1650508 ,  0.42506891],
       [ 0.48592737, -1.02724685, -0.80711386,  0.77650971],
       [ 0.34283337, -0.13244711, -0.33675267, -0.22622888]])

In [ ]:
a4.reshape(3,2)#we cannot change the size of the data which is 16.
#so we need to call the same size of the data
# multiplication of data must be equal to the total size of the data

In [47]:
a4.reshape(2,2,2,2)

array([[[[ 0.21580445,  0.29138881],
         [ 1.71443884, -1.12602486]],

        [[-0.58807136,  1.26883275],
         [-0.1650508 ,  0.42506891]]],


       [[[ 0.48592737, -1.02724685],
         [-0.80711386,  0.77650971]],

        [[ 0.34283337, -0.13244711],
         [-0.33675267, -0.22622888]]]])

In [48]:
a4.reshape(8,2)

array([[ 0.21580445,  0.29138881],
       [ 1.71443884, -1.12602486],
       [-0.58807136,  1.26883275],
       [-0.1650508 ,  0.42506891],
       [ 0.48592737, -1.02724685],
       [-0.80711386,  0.77650971],
       [ 0.34283337, -0.13244711],
       [-0.33675267, -0.22622888]])

In [49]:
a4.reshape(16,1)

array([[ 0.21580445],
       [ 0.29138881],
       [ 1.71443884],
       [-1.12602486],
       [-0.58807136],
       [ 1.26883275],
       [-0.1650508 ],
       [ 0.42506891],
       [ 0.48592737],
       [-1.02724685],
       [-0.80711386],
       [ 0.77650971],
       [ 0.34283337],
       [-0.13244711],
       [-0.33675267],
       [-0.22622888]])

In [52]:
a4.reshape(2,-24)#negative number will shape the data automatically

array([[ 0.21580445,  0.29138881,  1.71443884, -1.12602486, -0.58807136,
         1.26883275, -0.1650508 ,  0.42506891],
       [ 0.48592737, -1.02724685, -0.80711386,  0.77650971,  0.34283337,
        -0.13244711, -0.33675267, -0.22622888]])

In [53]:
a4.reshape(2,2,4)#reshaping to 3 dimensional array

array([[[ 0.21580445,  0.29138881,  1.71443884, -1.12602486],
        [-0.58807136,  1.26883275, -0.1650508 ,  0.42506891]],

       [[ 0.48592737, -1.02724685, -0.80711386,  0.77650971],
        [ 0.34283337, -0.13244711, -0.33675267, -0.22622888]]])

In [54]:
a4.reshape(1,1,1,1,1,2,2,4)#can be reshape to any sizes if multiplication is equal to the total size

array([[[[[[[[ 0.21580445,  0.29138881,  1.71443884, -1.12602486],
             [-0.58807136,  1.26883275, -0.1650508 ,  0.42506891]],

            [[ 0.48592737, -1.02724685, -0.80711386,  0.77650971],
             [ 0.34283337, -0.13244711, -0.33675267, -0.22622888]]]]]]]])

In [55]:
a1

array(['1', '2', '3', '4', 'rulu', '253.373', 'True'], dtype='<U32')

In [56]:
a1[0]

'1'

In [57]:
a1[2:6] #starts from 2nd index and excludes 6th index

array(['3', '4', 'rulu', '253.373'], dtype='<U32')

In [58]:
a1[2:6:2] #starts from 2 till 6 by taking jump of 2

array(['3', 'rulu'], dtype='<U32')

In [59]:
a1[::-1]#reverse function

array(['True', '253.373', 'rulu', '4', '3', '2', '1'], dtype='<U32')

In [60]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
a2[0]#extract first row

array([1, 2, 3])

In [64]:
a2[:,1:] #extracting 1,2 indexes from both rows, (:) represents rows

array([[2, 3],
       [5, 6]])

In [65]:
a2[[0,1], 1:]

array([[2, 3],
       [5, 6]])

In [67]:
a5 = np.random.randint(2,90, (6,5))

In [68]:
a5

array([[25, 66, 18, 41, 66],
       [42, 81,  3, 83, 45],
       [76, 41, 39, 81, 57],
       [71, 88,  6, 85, 61],
       [35,  2, 50, 63, 18],
       [37, 86, 88, 42, 15]])

In [69]:
a5[a5>40] #filter operation

array([66, 41, 66, 42, 81, 83, 45, 76, 41, 81, 57, 71, 88, 85, 61, 50, 63,
       86, 88, 42])

In [70]:
a5

array([[25, 66, 18, 41, 66],
       [42, 81,  3, 83, 45],
       [76, 41, 39, 81, 57],
       [71, 88,  6, 85, 61],
       [35,  2, 50, 63, 18],
       [37, 86, 88, 42, 15]])

In [71]:
a5[0,1] = 100 #replace value or assignment of value
a5

array([[ 25, 100,  18,  41,  66],
       [ 42,  81,   3,  83,  45],
       [ 76,  41,  39,  81,  57],
       [ 71,  88,   6,  85,  61],
       [ 35,   2,  50,  63,  18],
       [ 37,  86,  88,  42,  15]])

In [80]:
a6 = np.random.randint(0,3, (3,3))

In [81]:
a7 = np.random.randint(0, 3, (3,3))

In [82]:
a6

array([[2, 0, 2],
       [2, 0, 2],
       [2, 2, 0]])

In [83]:
a7

array([[2, 1, 1],
       [1, 2, 1],
       [1, 2, 0]])

In [84]:
a6*a7 #element to element multiplication on same index

array([[4, 0, 2],
       [2, 0, 2],
       [2, 4, 0]])

In [85]:
a6@a7 #matrix multiplication

array([[6, 6, 2],
       [6, 6, 2],
       [6, 6, 4]])

In [87]:
a6+100

array([[102, 100, 102],
       [102, 100, 102],
       [102, 102, 100]])

In [88]:
a6/0 #Numpy gives warning instead opf error as infinity exists inside numpy

C:\Users\atsuy\AppData\Local\Temp\ipykernel_16488\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\atsuy\AppData\Local\Temp\ipykernel_16488\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, nan, inf],
       [inf, nan, inf],
       [inf, inf, nan]])

In [90]:
a6**3 #squaring

array([[8, 0, 8],
       [8, 0, 8],
       [8, 8, 0]], dtype=int32)

In [93]:
a8 = np.zeros((4,4)) #zeros gives every element as zero

In [94]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
a9 = np.ones((4,5)) #ones gives every element as 1

In [97]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
a9 + np.array([1,2,3,4,5]) #adding elememts in row wise

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [99]:
a9 + np.array([1,2,3,4]) # array elements should have equal columns

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [106]:
a9 + np.array([[1,2,3,4]]).T #Transpose of the array 
#(transpose require 2 dimensional list i.e 2 list brackets)

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [107]:
a6

array([[2, 0, 2],
       [2, 0, 2],
       [2, 2, 0]])

In [108]:
a6.T

array([[2, 2, 2],
       [0, 0, 2],
       [2, 2, 0]])

In [110]:
np.sqrt(a5) #squareroot

array([[ 5.        , 10.        ,  4.24264069,  6.40312424,  8.1240384 ],
       [ 6.4807407 ,  9.        ,  1.73205081,  9.11043358,  6.70820393],
       [ 8.71779789,  6.40312424,  6.244998  ,  9.        ,  7.54983444],
       [ 8.42614977,  9.38083152,  2.44948974,  9.21954446,  7.81024968],
       [ 5.91607978,  1.41421356,  7.07106781,  7.93725393,  4.24264069],
       [ 6.08276253,  9.2736185 ,  9.38083152,  6.4807407 ,  3.87298335]])

In [111]:
np.exp(a5)# exponential

array([[7.20048993e+10, 2.68811714e+43, 6.56599691e+07, 6.39843494e+17,
        4.60718663e+28],
       [1.73927494e+18, 1.50609731e+35, 2.00855369e+01, 1.11286375e+36,
        3.49342711e+19],
       [1.01480039e+33, 6.39843494e+17, 8.65934004e+16, 1.50609731e+35,
        5.68572000e+24],
       [6.83767123e+30, 1.65163625e+38, 4.03428793e+02, 8.22301271e+36,
        3.10429794e+26],
       [1.58601345e+15, 7.38905610e+00, 5.18470553e+21, 2.29378316e+27,
        6.56599691e+07],
       [1.17191424e+16, 2.23524660e+37, 1.65163625e+38, 1.73927494e+18,
        3.26901737e+06]])

In [113]:
np.log10(a5) #logarithmic operation

array([[1.39794001, 2.        , 1.25527251, 1.61278386, 1.81954394],
       [1.62324929, 1.90848502, 0.47712125, 1.91907809, 1.65321251],
       [1.88081359, 1.61278386, 1.59106461, 1.90848502, 1.75587486],
       [1.85125835, 1.94448267, 0.77815125, 1.92941893, 1.78532984],
       [1.54406804, 0.30103   , 1.69897   , 1.79934055, 1.25527251],
       [1.56820172, 1.93449845, 1.94448267, 1.62324929, 1.17609126]])

In [118]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [119]:
list(range(0,10,2.5)) #floating point is not accepted in range

TypeError: 'float' object cannot be interpreted as an integer

In [122]:
np.arange(1.7, 10, 2.5) #floating accepts in arange

array([1.7, 4.2, 6.7, 9.2])

In [128]:
np.linspace(2,3, num = 50, retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [ ]:
# 0.02040816326530612 is the jump size from 2-3 

In [129]:
np.logspace(2,4, num = 4, base = 10) #in logarithmic term

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [130]:
np.eye(5) #eye is numpy identity matrix (identity matrix is where determinant =1)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [138]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [136]:
pip install cufflinks


  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68736 sha256=a680194dcc41c651003de2b21e5b97a39f1b05774facb5eee04ffea79aa8e5e3
  Stored in directory: c:\users\atsuy\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks


In [139]:
cf.go_offline()

In [145]:
df = pd.DataFrame(np.random.randn(100,3),columns = ['A', 'B', 'C'])

In [146]:
df

A         B         C
0  -0.376593  0.855256  0.536853
1   0.378303  2.906938  0.429987
2  -1.119419  0.002916 -0.764757
3   2.613498 -0.764474 -1.634602
4  -0.164121 -0.281745 -0.481988
..       ...       ...       ...
95  0.248368  0.049389  0.852420
96  0.266934 -0.819317  1.046411
97 -0.033153 -0.585943  0.938387
98  0.416706 -0.622227  0.152553
99 -0.482253 -0.454450 -0.379503

[100 rows x 3 columns]

In [147]:
df.iplot()

In [148]:
df1 = pd.DataFrame(np.random.randint(3,100, (100,1)))

In [149]:
df1

0
0    3
1   37
2   47
3   48
4   55
..  ..
95  43
96  64
97  70
98  81
99   3

[100 rows x 1 columns]

In [151]:
df1.iplot()

In [155]:
df.iplot(x= 'A', y = 'B', mode = 'markers')

In [157]:
df2 = sns.load_dataset('titanic')

In [159]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [163]:
df2.iplot(x = 'age', y = 'fare', mode = 'markers')

In [165]:
df2.iplot(x = 'age', y = 'pclass', mode = 'markers')

In [169]:
df2.iplot(x = 'fare', y = 'pclass', mode = 'markers')

In [170]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [180]:
df2.iplot(kind = 'bar', x = 'sex', y = 'survived')