In [1]:
import pandas as pd

In [23]:
data = {'name' : ["rulu", 'Randolf', 'John', 'Jenny'],
       'salary': [1000, 2000,3000, 400],
        'mail_id':['rulu@ineuron.ai', 'randolf@ineuron.ai', 'john@ineuron.ai', 'jenny@ineuron.ai'],
        'address': ['blr', 'us', 'blr', 'blr']
       }

In [24]:
df = pd.DataFrame(data)
#pd.DataFrame(data, columns = 1,2,3,4) to give column name

In [17]:
df

name  salary             mail_id address
0     rulu    1000     rulu@ineuron.ai     blr
1  Randolf    2000  randolf@ineuron.ai      us
2    John]    3000     john@ineuron.ai     blr
3    Jenny     400    jenny@ineuron.ai     blr

In [14]:
df.loc[6:7] #loc takes given value indexes

name  salary           mail_id address
6  John]    3000   john@ineuron.ai     blr
7  Jenny     400  jenny@ineuron.ai     blr

In [15]:
df.iloc[6:7] #iloc takes default(internal) indexes

Empty DataFrame
Columns: [name, salary, mail_id, address]
Index: []

In [26]:
data1 = {
    'pf_no' : [234, 4322, 2343, 233],
    'income_tax': [344,532,245,452],
    'mobile_no': [2342211234,4532273536, 2933847363, 2638293039],
    'courses': ['ds', 'big data', 'web dev', 'blockchain']
}

In [27]:
df1 = pd.DataFrame(data1)

In [28]:
df1

pf_no  income_tax   mobile_no     courses
0    234         344  2342211234          ds
1   4322         532  4532273536    big data
2   2343         245  2933847363     web dev
3    233         452  2638293039  blockchain

In [25]:
df

name  salary             mail_id address
0     rulu    1000     rulu@ineuron.ai     blr
1  Randolf    2000  randolf@ineuron.ai      us
2     John    3000     john@ineuron.ai     blr
3    Jenny     400    jenny@ineuron.ai     blr

In [29]:
pd.concat([df,df1])#vertical concatenation

name  salary             mail_id address   pf_no  income_tax  \
0     rulu  1000.0     rulu@ineuron.ai     blr     NaN         NaN   
1  Randolf  2000.0  randolf@ineuron.ai      us     NaN         NaN   
2     John  3000.0     john@ineuron.ai     blr     NaN         NaN   
3    Jenny   400.0    jenny@ineuron.ai     blr     NaN         NaN   
0      NaN     NaN                 NaN     NaN   234.0       344.0   
1      NaN     NaN                 NaN     NaN  4322.0       532.0   
2      NaN     NaN                 NaN     NaN  2343.0       245.0   
3      NaN     NaN                 NaN     NaN   233.0       452.0   

      mobile_no     courses  
0           NaN         NaN  
1           NaN         NaN  
2           NaN         NaN  
3           NaN         NaN  
0  2.342211e+09          ds  
1  4.532274e+09    big data  
2  2.933847e+09     web dev  
3  2.638293e+09  blockchain

In [30]:
pd.concat([df,df1], axis = 1)#complete horizontal

name  salary             mail_id address  pf_no  income_tax   mobile_no  \
0     rulu    1000     rulu@ineuron.ai     blr    234         344  2342211234   
1  Randolf    2000  randolf@ineuron.ai      us   4322         532  4532273536   
2     John    3000     john@ineuron.ai     blr   2343         245  2933847363   
3    Jenny     400    jenny@ineuron.ai     blr    233         452  2638293039   

      courses  
0          ds  
1    big data  
2     web dev  
3  blockchain

In [31]:
data2 = {'0' : ["rulu", 'Randolf', 'John', 'Jenny'],
       '1': [1000, 2000,3000, 400],
        '2':['rulu@ineuron.ai', 'randolf@ineuron.ai', 'john@ineuron.ai', 'jenny@ineuron.ai'],
        '3': ['blr', 'us', 'blr', 'blr']
       }

In [32]:
data3 = {
    '0' : [234, 4322, 2343, 233],
    '1': [344,532,245,452],
    '2': [2342211234,4532273536, 2933847363, 2638293039],
    '3': ['ds', 'big data', 'web dev', 'blockchain']
}

In [33]:
df2=pd.DataFrame(data2)

In [34]:
df3=pd.DataFrame(data3)

In [35]:
df2

0     1                   2    3
0     rulu  1000     rulu@ineuron.ai  blr
1  Randolf  2000  randolf@ineuron.ai   us
2     John  3000     john@ineuron.ai  blr
3    Jenny   400    jenny@ineuron.ai  blr

In [36]:
df3

0    1           2           3
0   234  344  2342211234          ds
1  4322  532  4532273536    big data
2  2343  245  2933847363     web dev
3   233  452  2638293039  blockchain

In [39]:
pd.concat([df2,df3])# same column name gives complete vertical concatenation

0     1                   2           3
0     rulu  1000     rulu@ineuron.ai         blr
1  Randolf  2000  randolf@ineuron.ai          us
2     John  3000     john@ineuron.ai         blr
3    Jenny   400    jenny@ineuron.ai         blr
0      234   344          2342211234          ds
1     4322   532          4532273536    big data
2     2343   245          2933847363     web dev
3      233   452          2638293039  blockchain

In [40]:
data4 = {
    'emp_id':[101,102,103,104],
    'salary':[203,302,204,205],
    'pf': [203,384,492,203],
}

In [58]:
data5 = {
    'emp_id':[101,102,105,104],
    'mobile_no':[220238393,2039473,302837362,293748],
    'house_no': [253,3726,2637,283]
}

In [50]:
df4 = pd.DataFrame(data4)

In [59]:
df5=pd.DataFrame(data5)

In [44]:
df4


emp_id  salary   pf
0     101     203  203
1     102     302  384
2     103     204  492
3     104     205  203

In [60]:
df5

emp_id  mobile_no  house_no
0     101  220238393       253
1     102    2039473      3726
2     105  302837362      2637
3     104     293748       283

In [63]:
pd.merge(df4,df5) #pd.merge operation identify and merges common element. Merge op takes column as common.

emp_id  salary   pf  mobile_no  house_no
0     101     203  203  220238393       253
1     102     302  384    2039473      3726
2     104     205  203     293748       283

In [64]:
pd.merge(df4,df5, how='left')#takes every data from the left

emp_id  salary   pf    mobile_no  house_no
0     101     203  203  220238393.0     253.0
1     102     302  384    2039473.0    3726.0
2     103     204  492          NaN       NaN
3     104     205  203     293748.0     283.0

In [65]:
pd.merge(df4,df5, how='right')#takes everything from the right

emp_id  salary     pf  mobile_no  house_no
0     101   203.0  203.0  220238393       253
1     102   302.0  384.0    2039473      3726
2     105     NaN    NaN  302837362      2637
3     104   205.0  203.0     293748       283

In [66]:
pd.merge(df4, df5, how ='right', on = 'emp_id')

emp_id  salary     pf  mobile_no  house_no
0     101   203.0  203.0  220238393       253
1     102   302.0  384.0    2039473      3726
2     105     NaN    NaN  302837362      2637
3     104   205.0  203.0     293748       283

In [67]:
data6 = {
    'emp_id1':[101,102,103,104],
    'salary':[203,302,204,205],
    'pf': [203,384,492,203],
}
data7 = {
    'emp_id2':[101,102,105,104],
    'mobile_no':[220238393,2039473,302837362,293748],
    'house_no': [253,3726,2637,283]
}

In [68]:
df6 = pd.DataFrame(data6)
df7= pd.DataFrame(data7)

In [70]:
pd.merge(df6,df7, left_on = 'emp_id1', right_on = 'emp_id2') #This consider the common key values.

emp_id1  salary   pf  emp_id2  mobile_no  house_no
0      101     203  203      101  220238393       253
1      102     302  384      102    2039473      3726
2      104     205  203      104     293748       283

In [93]:
data8 = {
    'emp_id':[101,102,103,104],
    'salary':[203,302,204,205],
    'pf': [203,384,492,203],
}
data9 = {
    'emp_id':[101,102,104,105,106],
    'salary':[203,302,204,205,209],
    'house_no': [253,3726,2637,283,209]
}

In [94]:
df8 = pd.DataFrame(data8)
df9 = pd.DataFrame(data9)

In [95]:
pd.merge(df8, df9, on = ['emp_id', 'salary'])

emp_id  salary   pf  house_no
0     101     203  203       253
1     102     302  384      3726

In [96]:
data10 = {
    'emp_id1':[101,102,103,104],
    'salary1':[203,302,204,205],
    'pf': [203,384,492,203],
}
data11 = {
    'emp_id2':[101,102,104,105,106],
    'salary2':[203,302,204,205,209],
    'house_no': [253,3726,2637,283,209]
}

In [97]:
df10 = pd.DataFrame(data10, index=['a','b','c','d'])
df11 = pd.DataFrame(data11, index=['a','b','d','e','f'])

In [98]:
df10

emp_id1  salary1   pf
a      101      203  203
b      102      302  384
c      103      204  492
d      104      205  203

In [99]:
df11


emp_id2  salary2  house_no
a      101      203       253
b      102      302      3726
d      104      204      2637
e      105      205       283
f      106      209       209

In [100]:
df10.join(df11)#join operation takes indexes as common

emp_id1  salary1   pf  emp_id2  salary2  house_no
a      101      203  203    101.0    203.0     253.0
b      102      302  384    102.0    302.0    3726.0
c      103      204  492      NaN      NaN       NaN
d      104      205  203    104.0    204.0    2637.0

In [102]:
df_sales = pd.read_csv('sales_data_final.csv')

In [104]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [108]:
def profit_flag(a):
    if a >=0:
        return 'positive'
    else:
        return 'negative'

In [109]:
profit_flag(-3)

'negative'

In [110]:
profit_flag(3)

'positive'

In [111]:
df_sales['Flag_profit'] = df_sales['profit'].apply(profit_flag)

In [112]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year Flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [113]:
df_sales['len_cus_name'] =df_sales['customer_name'].apply(len)

In [115]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  Flag_profit len_cus_name  
0          35.46          Medium  2011     positive           15  
1           9.72          Medium  2011     positive           11  
2           8.17            High  2011     positive           13  
3           4.82            High  2011     negative           12  
4           4.70          Medium  2011     positive           11  

[5 rows x 23 columns]

In [116]:
def quantity_flag(a):
    if a <10:
        return 'low'
    elif a>10 and a <20:
        return 'medium'
    else:
        return 'high'

In [120]:
df_sales['flag_quantity'] = df_sales['quantity'].apply(quantity_flag)

In [121]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  Flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   len_cus_name flag_quantity  
0            15           low  
1            11           low  
2            13           low  
3            12           low  
4            11           low  

[5 rows x 24 columns]

In [122]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a: a**2)

In [123]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  Flag_profit  \
0      0.0  106.140         35.46         Medium  2011     positive   
1      0.1   36.036          9.72         Medium  2011     positive   
2      0.0   29.640          8.17           High  2011     positive   
3      0.5  -26.055          4.82           High  2011     negative   
4      0.1   37.770          4.70         Medium  2011     positive   

   len_cus_name  flag_quantity square_quantity  
0            15            low               4  
1            11            low               9  
2            13            low              16  
3            12            low               9  
4            11            low              25  

[5 rows x 25 columns]

In [124]:
import numpy as np

In [126]:
np.array([2,2,3,4,5,6])

array([2, 2, 3, 4, 5, 6])

In [128]:
type(np.array([2,2,3,4,5,6]))

numpy.ndarray

In [130]:
np.array([[1,2,3,4],
        [2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [132]:
l=[[1,2,3,4], [2,3,4,5]]

In [134]:
l[0][0]

1

In [139]:
a=np.array([2,2,3,4,5,6], ndmin=3)

In [140]:
a

array([[[2, 2, 3, 4, 5, 6]]])

In [141]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [142]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
arr.ndim

2

In [146]:
np.random.randint(1,10,(4,4))

array([[1, 5, 8, 9],
       [9, 9, 7, 7],
       [7, 5, 5, 8],
       [2, 7, 7, 2]])

In [148]:
np.random.randint(1,10,(4,4,2))

array([[[7, 3],
        [1, 6],
        [3, 5],
        [9, 2]],

       [[4, 2],
        [5, 5],
        [8, 4],
        [9, 9]],

       [[5, 1],
        [1, 9],
        [9, 9],
        [5, 3]],

       [[3, 7],
        [4, 8],
        [6, 7],
        [6, 5]]])

### Task 31-07-2022

In [ ]:
#Task 1 - Fitbit Dataset

1. Read this dataset in pandas , mysql and mongodb 
2. while creting a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql
 ## hint - use csvkit library to automate this task and to load a data in bulk in you mysql 
3. convert all the dates avaible in dataset to timestamp format in pandas and in sql you to convert it in date format
4 . Find out in this data that how many unique id's we have 
5 . which id is one of the active id that you have in whole dataset 
6 . how many of them have not logged there activity find out in terms of number of ids 
7 . Find out who is the laziest person id that we have in dataset 
8 . Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset 
9. how many person are not a regular person with respect to activity try to find out those 
10 . who is the thired most active person in this dataset find out those in pandas and in sql both . 
11 . who is the 5th most laziest person avilable in dataset find it out 
12 . what is a totla acumulative calories burn for a person find out 


In [ ]:
#task 2 - Superstore_USA
1 . load this data in sql and in pandas with a relation in sql 
2 . while loading this data you dont have to create a table manually you can
use any automated approach to create a table and load a data in bulk in table 
3 . Find out how return that we ahve recived and with a product id 
4 . try  to join order and return data both in sql and pandas 
5 . Try to find out how many unique customer that we have 
6 . try to find out in how many regions we are selling a product and who is a 
manager for a respective region 
7 . find out how many different differnet shipement mode that we have and what 
is a percentage usablity of all the shipment mode with respect to dataset 
8 . Create a new coulmn and try to find our a diffrence between order date and
shipment date
9 . base on question number 8 find out for which order id we have shipment 
duration more than 10 days 
10 . Try to find out a list of a returned order which sihpment duration was
more then 15 days and find out that region manager as well 
11 . Gorup by region and find out which region is more profitable 
12 . Try to find out overalll in which country we are giving more didscount 
13 . Give me a list of unique postal code 
14 . which customer segement is more profitalble find it out . 
15 . try to find out the 10th most loss making product catagory . 
16 . Try to find out 10 top  product with highest margins 

submit your git link for the same 
 
you have to submit this task by next Friday 5th 11PM IST  to respective mail id 
sudhanshu@ineuron.ai , sunny.savita@ineuron.ai 

### Submit task by next Fri 5th Aug 11pm IST to sudhanshu@ineuron.ai and sunny.savita@inenurin.ai